# Simple filebeat configuration for ecommerce microservices

filebeat.inputs:
- type: container
  paths:
    - /var/log/containers/*.log

processors:
- add_kubernetes_metadata:
    host: ${NODE_NAME}

output.logstash:
  hosts: ["logstash-logstash.logging.svc.cluster.local:5044"]

logging.level: info