apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: sanjodb/api-gateway:prod
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "384Mi"
            cpu: "180m"
          limits:
            memory: "384Mi"
            cpu: "340m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: "file:/app/config/"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin-service:9411"
        - name: SPRING_ZIPKIN_ENABLED
          value: "true"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://cloud-config:9296"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "true"
        - name: SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED
          value: "false"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
          value: "zipkin"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          value: "http://zipkin-service:9411"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
          value: "Path=/zipkin/**"
        # - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
        #   value: "StripPrefix=1"
        # --- RUTA GENÉRICA PARA TODAS LAS APIs DE NEGOCIO VÍA PROXY-CLIENT (índice 2) ---
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
          value: "proxy_client_business_apis"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
          value: "lb://PROXY-CLIENT"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
          value: "Path=/api/**"     # <--- CAMBIADO A /api/**
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ORDER 
          value: "-1" # <--- ORDEN PARA DARLE PRECEDENCIA
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0_NAME
          value: "RewritePath"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0_ARGS_REGEXP
          value: "/api/(?<segment>.*)" # Captura todo después de /api/
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0_ARGS_REPLACEMENT
          value: "/app/api/$\\{segment}" # Lo reenvía a /app/api/... al proxy-client

        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"

        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
          value: "eureka"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
          value: "http://service-discovery:8761"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
          value: "Path=/eureka/**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
          value: "RewritePath=/eureka/(?<segment>.*), /$\\{segment}"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: CLIENT_HOST
          value: "http://localhost:4200"
        - name: SPRING_APPLICATION_NAME
          value: "API-GATEWAY"
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: common-config-volume
          mountPath: /app/config
      volumes:
      - name: common-config-volume
        configMap:
          name: common-config
          items:
            - key: "common-services.properties"
              path: "common-services.properties"
            - key: "api-gateway.properties"
              path: "api-gateway.properties"