apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  # namespace: ecommerce-app
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: sanjodb/payment-service:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8400
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "350m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/app/config/"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin-service:9411"
            - name: SPRING_ZIPKIN_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://cloud-config:9296"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "PAYMENT-SERVICE"
            - name: SERVER_PORT
              value: "8400"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/payment-service"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_HEALTH_CIRCUITBREAKERS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            # Variables para estabilizar la inicialización
            - name: SPRING_CLOUD_REFRESH_ENABLED
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dspring.cloud.loadbalancer.ribbon.enabled=false"
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
          startupProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 20
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 8
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config
            items:
              - key: "common-services.properties"
                path: "common-services.properties"
              - key: "payment-service.properties"
                path: "payment-service.properties" 